Added ImageUrl field for Products
Pilkas-git/PSKApi pull request #9
Opened 2021-05-14 18:14 UTC by T-aut

Small PR which adds a new field for image urls

Decided to use https://cloudinary.com/ for cloud image storage. Will have to add images for all test products.

2021-05-14 18:35 UTC, Pilkas-git requested changes
Small changes.

2021-05-14 18:35 UTC, Pilkas-git commented on src/FlowerShop.Core/Entities/Product.cs
> +        [MaxLength(150)]
Define max MaxLength in entity configuration not on entity as data annotation

2021-05-14 18:35 UTC, Pilkas-git commented on src/FlowerShop.Core/Entities/Product.cs
> +        public Product(string name, decimal price, string description, ProductType productType, string imageUrl)
unnecessary constructor if image is not necessary for product to exist it should not be in the constructor. Define a basic set method in the entity itself it helps to keep track of all the references where imageUrl will be changed and if it needs to be changed all the logic can easily tracked with references.

2021-05-14 19:05 UTC, T-aut commented on src/FlowerShop.Core/Entities/Product.cs
> +        [MaxLength(150)]
I'm afraid to do any more migrations, since the Order System branch has quite a few (should probably merge it first?)

2021-05-16 12:55 UTC, closed without merging

2021-05-16 12:56 UTC, T-aut commented
Merged into surinkom-5/PSKApi